### ISSUE TITLE
Jekyll build is broken

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fortran-lang.org#184]
See https://github.com/fortran-lang/fortran-lang.org/actions/runs/431313773

```
Run cd src
  cd src
  sudo gem install bundler
  bundle config path .bundle
  bundle install
  shell: /bin/bash -e {0}
  env:
    SRC_DIR: src
    PUBLISH_DIR: gh-pages
    SITE_URL: https://fortran-lang.org
    FPM_INDEX: https://raw.githubusercontent.com/fortran-lang/fpm-registry/master/index.json
Successfully installed bundler-2.2.2
Parsing documentation for bundler-2.2.2
Installing ri documentation for bundler-2.2.2
Done installing documentation for bundler after 3 seconds
1 gem installed
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
	from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
	from /usr/local/bin/bundle:23:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by awvwgk** [comment]
Looks like the Jekyll build workflow is actually broken.

**Comment by LKedward** [comment]
This might be an issue with the lock file, updating it might help.

**Comment by LKedward** [comment]
Looks like this is related to <https://github.com/actions/virtual-environments/issues/2193> which may be fixed by using <https://github.com/ruby/setup-ruby>. I will test on my branch
